In [30]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import requests
import re
import string
import random

import warnings
warnings.filterwarnings("ignore")

from nltk.corpus import stopwords
from sklearn.metrics.pairwise import linear_kernel
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.tokenize import RegexpTokenizer
from PIL import Image
from io import BytesIO
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
data = pd.read_csv(r"C:\Users\Vansh\Downloads\odoo finals\books.csv")

In [3]:
data

,isbn13,isbn10,title,subtitle,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count
0,9780002005883,0002005883,Gilead,NaN,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0
1,9780002261982,0002261987,Spider's Web,A Novel,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0
2,9780006163831,0006163831,The One Tree,NaN,Stephen R. Donaldson,American fiction,http://books.google.com/books/content?id=OmQaw...,Volume Two of Stephen Donaldson's acclaimed se...,1982.0,3.97,479.0,172.0
3,9780006178736,0006178731,Rage of angels,NaN,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0
4,9780006280897,0006280897,The Four Loves,NaN,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0
...,...,...,...,...,...,...,...,...,...,...,...,...
6805,9788185300535,8185300534,I Am that,Talks with Sri Nisargadatta Maharaj,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0
6806,9788185944609,8185944601,Secrets Of The Heart,NaN,Khalil Gibran,Mysticism,http://books.google.com/books/content?id=XcrVp...,NaN,1993.0,4.08,74.0,324.0
6807,9788445074879,8445074873,Fahrenheit 451,NaN,Ray Bradbury,Book burning,NaN,NaN,2004.0,3.98,186.0,5733.0
6808,9789027712059,9027712050,The Berlin Phenomenology,NaN,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0
6809,9789042003408,9042003405,'I'm Telling You Stories',Jeanette Winterson and the Politics of Reading,Helena Grice;Tim Woods,Literary Criticism,http://books.google.com/books/content?id=2lVyR...,This is a jubilant and rewarding collection of...,1998.0,3.70,136.0,10.0

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6810 entries, 0 to 6809
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   isbn13          6810 non-null   int64
 1   isbn10          6810 non-null   object
 2   title           6810 non-null   object
 3   subtitle        2381 non-null   object
 4   authors         6738 non-null   object
 5   categories      6711 non-null   object
 6   thumbnail       6481 non-null   object
 7   description     6548 non-null   object
 8   published_year  6804 non-null   float64
 9   average_rating  6767 non-null   float64
 10  num_pages       6767 non-null   float64
 11  ratings_count   6767 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 638.6+ KB

In [5]:
data.isnull().sum()

isbn13               0
isbn10               0
title                0
subtitle          4429
authors             72
categories          99
thumbnail          329
description        262
published_year       6
average_rating      43
num_pages           43
ratings_count       43
dtype: int64

In [6]:
data = data.drop('subtitle', axis=1)
data = data.drop('thumbnail', axis = 1)

In [7]:
data.head()

,isbn13,isbn10,title,authors,categories,description,published_year,average_rating,num_pages,ratings_count
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0
2,9780006163831,0006163831,The One Tree,Stephen R. Donaldson,American fiction,Volume Two of Stephen Donaldson's acclaimed se...,1982.0,3.97,479.0,172.0
3,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0
4,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0

In [8]:
data.dropna(subset=['average_rating'], inplace=True)

In [9]:
data.dropna(subset=['published_year'], inplace=True)

In [10]:
data.dropna(subset=['authors'], inplace=True)

In [11]:
data.isnull().sum()

isbn13              0
isbn10              0
title               0
authors             0
categories         93
description       248
published_year      0
average_rating      0
num_pages           0
ratings_count       0
dtype: int64

In [12]:
data['published_year'] = data['published_year'].astype(int)
data['num_pages'] = data['num_pages'].astype(int)
data['ratings_count'] = data['ratings_count'].astype(int)

In [13]:
data['average_rating'] = data['average_rating'].round(0).astype(int)

In [14]:
data.isnull().sum()

isbn13              0
isbn10              0
title               0
authors             0
categories         93
description       248
published_year      0
average_rating      0
num_pages           0
ratings_count       0
dtype: int64

In [15]:
data.dropna(subset=['description'], inplace=True)
data.dropna(subset=['categories'], inplace=True)

In [16]:
data.isnull().sum()

isbn13            0
isbn10            0
title             0
authors           0
categories        0
description       0
published_year    0
average_rating    0
num_pages         0
ratings_count     0
dtype: int64

In [17]:
data.head()

,isbn13,isbn10,title,authors,categories,description,published_year,average_rating,num_pages,ratings_count
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,A NOVEL THAT READERS and critics have been eag...,2004,4,247,361
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,A new 'Christie for Christmas' -- a full-lengt...,2000,4,241,5164
2,9780006163831,0006163831,The One Tree,Stephen R. Donaldson,American fiction,Volume Two of Stephen Donaldson's acclaimed se...,1982,4,479,172
3,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,"A memorable, mesmerizing heroine Jennifer -- b...",1993,4,512,29532
4,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,Lewis' work on the nature of love divides love...,2002,4,170,33684

In [18]:
data = data[~data.description.str.contains('[0-9].*[0-9].*[printing]')]
#removing numbers of printing info from description

In [28]:
# REMOVE NON ASCII CHARACTERS
def remove_non_ascii(string):
    return "".join(c for c in string if ord(c) < 128)

# MAKE DESCRIPTION TEXT LOWER CASE
def make_lower_case(text):
    return text.lower()

# REMOVE STOP WORDS
def remove_stop_words(text):
    text = text.split()
    stops = set(stopwords.words('english'))
    text = [word for word in text if not word in stops]
    text = " ".join(text)
    return text

# REMOVE PUNCTUATIONS
def remove_punctuation(text):
    tokenizer = RegexpTokenizer(r'\w+')
    text = tokenizer.tokenize(text)
    text = " ".join(text)
    return text

# REMOVE HTML CODES
def remove_html(text):
    html_pattern = re.compile('<.*?>')
    return html_pattern.sub(r'', text)

In [31]:
data['cleaned_description'] = data['description'].apply(remove_non_ascii)
data['cleaned_description'] =data.cleaned_description.apply(make_lower_case)
data['cleaned_description'] = data.cleaned_description.apply(remove_stop_words)
data['cleaned_description'] = data.cleaned_description.apply(remove_punctuation)
data['cleaned_description'] = data.cleaned_description.apply(remove_html)

In [109]:
data.head()

,isbn13,isbn10,title,authors,categories,description,published_year,average_rating,num_pages,ratings_count,cleaned_description
2,9780006163831,0006163831,The One Tree,Stephen R. Donaldson,American fiction,Volume Two of Stephen Donaldson's acclaimed se...,1982,4,479,172,volume two stephen donaldson s acclaimed secon...
3,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,"A memorable, mesmerizing heroine Jennifer -- b...",1993,4,512,29532,memorable mesmerizing heroine jennifer brillia...
4,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,Lewis' work on the nature of love divides love...,2002,4,170,33684,lewis work nature love divides love four categ...
5,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,"""In The Problem of Pain, C.S. Lewis, one of th...",2002,4,176,37569,in problem pain c s lewis one renowned christi...
6,9780006353287,0006353282,An Autobiography,Agatha Christie,"Authors, English",Donation.,1977,4,560,3975,donation

In [107]:
def recommend(title, category):
    
    # MATCH THE CATEGORY WITH THE COLUMN "CATEGORIES" OF THE DATASET
    
    newdata = data.loc[data['categories'] == category] 
    # RESET INDEX
    newdata.reset_index(level = 0, inplace = True) 
    
    # INDEX TO A PANDAS SERIES
    indices = pd.Series(newdata.index, index = newdata['title'])
    
    # CONVERT THE BOOK TITLE INTO VECTORS AND USE BIGRAM
    tf = TfidfVectorizer(analyzer='word', ngram_range=(2, 2), min_df = 1, stop_words='english')
    tfidf_matrix = tf.fit_transform(newdata['cleaned_description'])
    
    # CALCULATE THE SIMILARITY MEASURE
    similarity = cosine_similarity(tfidf_matrix, tfidf_matrix)
    
    # GET THE INDEX OF ORIGINAL TITLE
    index = indices[title]
    
    # PAIRWISE SIMILARITY SCORES
    similarity = list(enumerate(similarity[index]))
    # SORT THE BOOKS
    similarity = sorted(similarity, key=lambda x: x[1], reverse=True)
    
    # GET TOP 5 MOST SIMILAR BOOKS
    similarity  = similarity [1:6]
    
    # INDICES OF TOP 5
    book_indices = [i[0] for i in similarity]

    # TOP 5 RECOMMENDATION
    rec = newdata[['title','isbn10']]
    isb = newdata.isbn10
    isb.astype(str)
    new = []
    for i in isb:
        for j in l1:
            if i==j:
                new.append(i)
            else:
                continue
    print(new[0:5])

In [108]:
recommend("Taken at the Flood", "Fiction")

['0006178731', '0007121016', '0060502959', '0060506040', '0060510854']

In [104]:
l1 = ["0006178731",
      "0007120818",
"0007120869",
'0007120877',
"0007120982",
"0007121008",
"0007121016",
"0007121024",
"0007121105",
"0007122586",
"0007124015",
"0007129653",
"0007130317",
"0007136595",
"0007137338",
"0007149123",
"000715030X",
"0007151241",
"0007151675",
"0007153589",
"0007154844",
"0007154887",
"0007158513",
"0007158521",
"0007171994",
"000717313X",
"0060278420",
"0060502959",
"0060504080",
"0060506040",
"0060509058",
"0060510854",
"0060511060",
"0060511109",
"0060511133",
"0060511141",
"0060513098",
"0060515198",
"0060515228",
"0060518650",
"0060519134",
"0060521228",
"0060524936",
"006052510X",
"0060527986",
"0060527994",
"0060529571",
"0060535113",
"0060539097",
"0060539259",
"0060541814"]

In [65]:
print(data['isbn10'][30:55])

48    0007120818
49    0007120869
50    0007120877
52    0007120982
53    0007121008
54    0007121016
55    0007121024
56    0007121105
57    0007122586
58    0007124015
61    0007129653
62    0007130317
65    0007136595
66    0007137338
67    0007149123
70    000715030X
71    0007151241
72    0007151675
73    0007153589
74    0007154844
75    0007154887
77    0007158513
78    0007158521
80    0007171994
82    000717313X
Name: isbn10, dtype: object

In [66]:
print(data['isbn10'][100:125])

139    0060278420
141    0060502959
142    0060504080
143    0060506040
145    0060509058
146    0060510854
148    0060511060
149    0060511109
151    0060511133
152    0060511141
154    0060513098
155    0060515198
156    0060515228
158    0060518650
159    0060519134
160    0060521228
162    0060524936
163    006052510X
165    0060527986
166    0060527994
167    0060529571
169    0060535113
170    0060539097
171    0060539259
173    0060541814
Name: isbn10, dtype: object